trigger:
  branches:
    include:
      - main

resources:
  repositories:
  - repository: self
  - repository: templates
    type: github
    name: equinor/procosys-infra
    endpoint: 'procosys - github'

# Global variables for the pipeline
variables:
- template: templates/variables/procosys-global-variables.yml@templates

- name: 'repositoryName'
  value: 'config/api'

stages:
# Build stage. Docker build, tag and push
- stage: build
  displayName: 'Build'
  dependsOn: ''
  variables:
    envName: 'build'
    containerRegistry: '${{ variables.containerRegistryName }}'
    envGroupName: '$(globalPrefix)-config-api-${{ variables.envName }}'
    dockerRegistryServiceConnection: '$(dockerRegistryServiceConnectionName)'
    dockerfilePath: '$(Build.SourcesDirectory)/src/Equinor.ProCoSys.Config/Dockerfile'

  jobs:
  # Docker Build Not Main
  - template: /templates/pipelines/dockerbuild-config-api.yml@templates
    parameters:
      dependsOn: ''
      deploymentName: 'docker_build'
      condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
      envGroup: '${{ variables.envGroupName }}'
      buildCommand: build
      dockerfilePath: '${{ variables.dockerfilePath }}'
      buildContext: '$(Build.SourcesDirectory)/src/Equinor.ProCoSys.Config'
      repository: '${{ variables.repositoryName }}'
      dockerRegistryServiceConnection: '$(dockerRegistryServiceConnectionName)'

  # Docker Build Main
  - template: /templates/pipelines/dockerbuild-config-api.yml@templates
    parameters:
      dependsOn: ''
      deploymentName: 'docker_build_push'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      envGroup: '${{ variables.envGroupName }}'
      buildCommand: buildAndPush
      dockerfilePath: '${{ variables.dockerfilePath }}'
      buildContext: '$(Build.SourcesDirectory)/src/Equinor.ProCoSys.Config'
      repository: '${{ variables.repositoryName }}'
      dockerRegistryServiceConnection: '$(dockerRegistryServiceConnectionName)'

# Release stage
- stage: release
  displayName: 'Release'
  dependsOn: 'build'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
    envName: 'release'
    envRg: 'pcs-config-non-prod-rg'
    envGroupName: '$(globalPrefix)-config-api-${{ variables.envName }}'
    serviceConnection: '${{ variables.nonProdServiceConnection }}'
    containerRegistry: '${{ variables.containerRegistryName }}' 

  jobs:
  # Release to Function App
  - template: /templates/pipelines/config-api-release.yml@templates
    parameters:
      dependsOn: ''
      deploymentName: 'release_to_function_app'
      serviceConnection: '${{ variables.serviceConnection }}'
      envRg: '${{ variables.envRg }}'
      envGroup: '${{ variables.envGroupName }}'
      dockerImage: '${{ variables.containerRegistry }}.azurecr.io/${{ variables.repositoryName }}:$(Build.BuildId)'
      functionApp: 'pcs-config-non-prod-func'