trigger:
  paths:
    include:
      - commissioning-webapp/*

resources:
  repositories:
  - repository: self
  - repository: templates
    type: github
    name: equinor/procosys-infra
    endpoint: 'procosys - github'

# Global variables for the pipeline
variables:
  - template: templates/variables/procosys-global-variables.yml@templates
  - template: templates/variables/wcm-variables.yml@templates
  - name: 'repositoryName'
    value: 'wcm/functions'
  - name: 'buildConfiguration'
    value: 'Release' 
  - name: 'vmImageName'
    value: 'ubuntu-latest'